name: Dummy Workflow

on:
  push:
    branches:
      - main

jobs:
  dummy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print a Message
        run: |
          echo "Hello, this is a dummy workflow!"
          echo "You can customize this workflow by adding more steps."

